
name: CI

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0 
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test
      - name: Publish
        run: dotnet publish ./UniAPI/UniAPI.csproj  -c Release -o ${{env.DOTNET_ROOT}}/api
  deploy-dev:
   runs-on: ubuntu-latest
   needs: build
   steps:
      
